### ISSUE TITLE
snow (layers=8) not rendered (2.0 Bug)

### ISSUE THREAD

**Issue by jackjt8** [leMaik/chunky#2]
snow layers render correctly in game and in Chunky 1.X.
![2020-02-23_10 05 45](https://user-images.githubusercontent.com/3740917/75110274-1c30e800-5624-11ea-933a-d1e0839e876f.png)

However in Chunky 2.X snow (layer=8) is not rendered.

![Untitled](https://user-images.githubusercontent.com/3740917/75110234-b5abca00-5623-11ea-9466-42979669c665.png) - NB layers [1] [8] [7]

Credits: TurtleRunsSlow

**Comment by leMaik** [comment]
Thanks for reporting this. Turns out that not only was level=8 not rendered, but in fact all layers were shifted.

Before:
![default-500](https://user-images.githubusercontent.com/5544859/75115314-7e5a0f00-565d-11ea-900d-585163612231.png)

After:
![image](https://user-images.githubusercontent.com/5544859/75115319-8a45d100-565d-11ea-920c-7f8577ec8713.png)

(fixed in f2c58bfa6ad2fc67d018d26d968a940a1592a25d)
