### ISSUE TITLE
Chunky not loading saved Actors/Entities

### ISSUE THREAD

**Issue by jackjt8** [leMaik/chunky#7]
Chunky will not load Actors/Entities even if they exist in the scene .json.

**Steps:**
1. Create a scene
2. Place Entity/Actor if there isn't one
3. Save Scene
4. Check scene .json file under they key "actors" & actor(s) will be present
5. Load scene and Chunky will not load the actors from the scene

**Versions tested:**
`1.4.5`, `1.4.6beta2`, `2.0beta6`, `LeMaik-197`

**Comment by jackjt8** [comment]
[YouTube Video of issue](https://youtu.be/uvfY3qTBdxk)

**Comment by leMaik** [comment]
@jackjt8 Thanks for your help to find the root of this bug. :+1: 

For the record: Actors didn't load if there were no other entities in the scene. My scene had campfires and lecterns in it (yes, campfires are entities in Chunky because they are higher than one block) so I couldn't reproduce this in my test scene.
